name: Test PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print PR SHA
        run: |
          echo "${{github.event.pull_request.head.sha}}"
          if [[ ${{github.event.pull_request.head.sha}} ]]
          then
            echo "PR"
          else
            ehco "Push"
          fi
