name: Test PRs

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set the SHA
        run: |
          echo "${{github.event.pull_request.head.sha}}"
          if [[ "${{github.event.pull_request.head.sha}}" != "" ]]
          then
            echo "PR"
            echo "ARTIFACT_SHA=$(echo ${{github.event.pull_request.head.sha}}" >> $GITHUB_ENV
          else
            echo "Push"
            echo "ARTIFACT_SHA=$(echo ${{github.sha}}" >> $GITHUB_ENV
          fi

      - name: Print the SHA
        run: echo $ARTIFACT_SHA
